# Air config file (https://github.com/cosmtrek/air)

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bin/main.exe cmd/app/main.go"
bin = "tmp/bin/main.exe"
log = "air_errors.log"
include_ext = ["go", "yaml", "json"]
exclude_dir = ["tmp"]
delay = 1000

[log]
time = true

[watcher]
use_polling = true
poll_interval = "100ms"

[misc]
clean_on_exit = true



