version: '3.2'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12.0-alpine
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/${DB_NAME}
    volumes:
      - ./scripts/database-scripts:/docker-entrypoint-initdb.d
      - .docker/postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'